# Generated by Django 5.0 on 2023-12-19 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("study", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="student",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="студент"
            ),
        ),
        migrations.AddField(
            model_name="materials",
            name="study_materials",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="study.study",
                verbose_name="материалы обучения",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="test_materials",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="study.materials",
                verbose_name="материалы теста",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="study.test",
                verbose_name="тест",
            ),
        ),
    ]
